---
title: "TRGN_510_final"
author: "bo"
date: "11/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
rm(list = ls())
```

### make a new function to put each htseqcounts data as a df
```{r}
predata <- function(val) {
  df = myfilelist[val]
  df <- as.data.frame(df)
  df <- data.frame(df[,-1], row.names = df[,1])
  colnames(df) <- myfilename[val]
  print(df)
}
```
## First we put all stage_i datasets
```{r}
mypath <- "./training_data/stage_i_htseqdata/"
myfilepath <- list.files("./training_data/stage_i_htseqdata/", pattern = "htseq", full.names = TRUE)
myfilename <- list.files(mypath, pattern = "htseq")
```

```{r}
myfilelist <- lapply(myfilepath, read.table)
```

```{r}
p <- predata(1)
library(dplyr)
for (i in 2:20){
  p=merge(p,predata(i),by = 0, all = T)
  p <- data.frame(p[,-1], row.names = p[,1])
}
```
## Second we put all stage_iia datasets
```{r}
mypath <- "training_data/stage_iia_htseqdata/"
myfilepath <- list.files(mypath,pattern = "htseq", full.names = TRUE)
myfilename <- list.files(mypath, pattern = "htseq")
myfilelist <- lapply(myfilepath, read.table)
q <- predata(1)
library(dplyr)
for (i in 2:20){
  q=merge(q,predata(i),by = 0, all = T)
  q <- data.frame(q[,-1], row.names = q[,1])
}
```
### Then we merge the two stage data
```{r}
df_all=merge(p,q,by=0,all=T)
df_all <- data.frame(df_all[,-1], row.names = df_all[,1])
df_all1111 <- df_all1111[-1,]
df <- df_all1111
```
## Find the significant genes
### we add class on the our df_all
```{r}
class <- data.frame(condition = factor(rep(c("i","iia"),c(20,20))))
class
```
### DESeq2
```{r}
library(DESeq2)
set.seed(2128)
vars <- sort(apply(df, 1, var, na.rm = TRUE), decreasing = TRUE)
data <- df[names(vars)[1:100],]
nTest <- ceiling(ncol(data) * 0.3)
ind <- sample(ncol(data),nTest,FALSE)
```
### Minimum count is set to 1 
```{r}
data.train <- as.matrix(data[ ,-ind] + 1)
data.test <- as.matrix(data[ ,ind] + 1)
classtr <- DataFrame(condition = class[-ind, ])
classts <- DataFrame(condition = class[ind, ])
```
### Now we have the traning and test sets
```{r}
data.trainS4 = DESeqDataSetFromMatrix(countData = data.train, colData = classtr,
design = formula(~condition))
data.testS4 = DESeqDataSetFromMatrix(countData = data.test, colData = classts,
design = formula(~condition))
```


